In [1]:
import requests
import json
from bs4 import BeautifulSoup
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML, Markdown
from datetime import datetime
import xml.etree.ElementTree as ET
import locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
from datetime import datetime
import pandas as pd
import time
import qgrid
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

C:\Users\daron\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
# # Initialize the variables
# CIKNumber = '0000027419'
# filingType = "10-K"
# selected_fiscal_year = 2021
# selected_quarter = 1  # Default to Q1

# # Create widgets for each variable
# cik_number_widget = widgets.Text(value=CIKNumber, description='CIK Number:')

# filing_type_widget = widgets.Dropdown(
#     options=['10-K', '10-Q'],
#     value=filingType,
#     description='Filing Type:'
# )

# fiscal_year_widget = widgets.Dropdown(
#     options=range(2000, datetime.now().year + 1),  # Adjust the range as needed
#     value=selected_fiscal_year,
#     description='Fiscal Year:'
# )

# quarter_widget = widgets.Dropdown(
#     options=[1, 2, 3, 4],
#     value=selected_quarter,
#     description='Quarter:',
#     layout={'visibility': 'hidden'}  # Initially hidden
# )

# # Create a button widget
# update_button = widgets.Button(description="Update Variables")

# # Function to toggle the visibility of the quarter widget
# def toggle_quarter_widget(change):
#     if change.new == '10-Q':
#         quarter_widget.layout.visibility = 'visible'
#     else:
#         quarter_widget.layout.visibility = 'hidden'

# # Attach the toggle function to the filing type widget
# filing_type_widget.observe(toggle_quarter_widget, names='value')

# # Display the widgets and button
# display(cik_number_widget)
# display(filing_type_widget)
# display(fiscal_year_widget)
# display(quarter_widget)
# display(update_button)

# output = widgets.Output()

# # Function to update the variables
# @output.capture()
# def update_variables(change):
#     global CIKNumber, filingType, selected_fiscal_year, selected_quarter
#     new_CIKNumber = cik_number_widget.value
#     if len(new_CIKNumber) != 10:
#         print("CIK Number must have exactly 10 characters.")
#     else:
#         global CIKNumber, filingType, selected_fiscal_year, selected_quarter
#         CIKNumber = new_CIKNumber
#         filingType = filing_type_widget.value
#         selected_fiscal_year = fiscal_year_widget.value
#         selected_quarter = quarter_widget.value
#         print("Variables updated successfully.")

# # Attach the update function to button click event
# update_button.on_click(update_variables)
# display(output)

In [3]:
# Initialize the variables
CIKNumber = '0000027419'
filingType = "10-K"
start_date = datetime(2021, 1, 1)
end_date = datetime(2021, 12, 30)

# Create widgets for each variable
cik_number_widget = widgets.Text(value=CIKNumber, description='CIK Number:') 

filing_type_widget = widgets.Dropdown(
    options=['10-K', '10-Q'],
    value=filingType,
    description='Filing Type:'
)
start_date_widget = widgets.DatePicker(value=start_date, description='Start Date:')
end_date_widget = widgets.DatePicker(value=end_date, description='End Date:')

# Create a button widget
update_button = widgets.Button(description="Update Variables")

# Display the widgets and button
display(cik_number_widget)
display(filing_type_widget)
display(start_date_widget)
display(end_date_widget)
display(update_button)

output = widgets.Output()

# Function to update the variables
@output.capture()
def update_variables(change):
    global CIKNumber, filingType, start_date, end_date
    new_CIKNumber = cik_number_widget.value
    if len(new_CIKNumber) != 10:
        with output:
            clear_output(wait=True)  # Clear the previous output and wait for new output
            print("CIK Number must have exactly 10 characters.")
    else:
        global CIKNumber, filingType, start_date, end_date
        CIKNumber = new_CIKNumber
        filingType = filing_type_widget.value
        start_date = start_date_widget.value
        end_date = end_date_widget.value
        with output:
            clear_output(wait=True)  # Clear the previous output and wait for new output
            print("Variables updated successfully.")
            time.sleep(2)  # Wait for 2 seconds
            clear_output()  # Clear the success message

# Attach the update function to the button click event
update_button.on_click(update_variables)
display(output)

Text(value='0000027419', description='CIK Number:')

Dropdown(description='Filing Type:', options=('10-K', '10-Q'), value='10-K')

DatePicker(value=datetime.datetime(2021, 1, 1, 0, 0), description='Start Date:')

DatePicker(value=datetime.datetime(2021, 12, 30, 0, 0), description='End Date:')

Button(description='Update Variables', style=ButtonStyle())

Output()

Purpose:
The provided widget setup allows for interactive updating of variables (CIKNumber, filingType, start_date, end_date) in a Jupyter Notebook environment. Users can modify these variables using widgets, and the provided button triggers the update.

Variable Initialization:

1. CIKNumber:
Description: The Central Index Key (CIK) number for the company.
Usage: Replace the initial value with the CIK number of the specific company you are interested in.

2. filingType:
Description: The initial filing type to be used.
Usage: Specify the initial filing type ('10-K', '10-Q') based on your requirements.

3. start_date and end_date:
Description: The initial date range for the filings.
Usage: Set the initial start and end dates in the 'YYYY-MM-DD' format based on your requirements.

Widgets:

1. cik_number_widget:
Type: Text
Description: A text input widget for modifying the CIK number interactively.

2. filing_type_widget:
Type: Dropdown
Options: '10-K', '10-Q'
Description: A dropdown menu for selecting the filing type interactively.

3. start_date_widget and end_date_widget:
Type: Date Picker
Description: Date picker widgets for selecting the start and end dates interactively.

4. update_button:
Type: Button
Description: A button widget triggering the update of variables when clicked.

Functionality:

1. Variable Update Function (update_variables):
Description: Updates the global variables (CIKNumber, filingType, start_date, end_date) based on the values entered in the widgets.
Validation: Checks that the CIK number has exactly 10 characters.
Output: Provides feedback on the success or failure of the variable update.

2. Output Widget (output):
Type: Output
Description: Displays messages about the success or failure of variable updates.
Clearing: Clears the output after a brief delay to remove the success message.

Usage:

1. Run the cell to display the widgets and the button.
2. Modify the values in the widgets interactively.
3. Click the "Update Variables" button to apply the changes.
4. Observe the output for success or failure messages.

Important Note:
Ensure that the notebook environment supports the widgets module, and consider adjusting the code if running outside of a Jupyter Notebook environment.

Modify the initial values and use the widgets to interactively update variables based on your specific requirements for the analysis or exploration of SEC filings.

In [4]:
class SecFilingDownloader:
    def __init__(self, CIKNumber, filingType, start_date, end_date):
        self.baseURL = "https://www.sec.gov"
        self.CIKNumber = CIKNumber
        self.filingType = filingType
        self.start_date = start_date
        self.end_date = end_date
        self.header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}
        self.apiData = None
        self.data = {"statement": []}
    
    def download_api_data(self):
        try:
            apiResponse = requests.get(f"https://data.sec.gov/api/xbrl/companyfacts/CIK{self.CIKNumber}.json", headers=self.header)
            apiResponse.raise_for_status()
            self.apiData = json.loads(apiResponse.content)
        except requests.exceptions.RequestException as e:
            print(f"API Request Error: {e}")
        except json.JSONDecodeError as e:
            print(f"JSON Decode Error: {e}")
    
    def download_company_filing(self):
        if self.apiData:
            filingParameters = {
                'action': 'getcompany',
                'CIK': self.CIKNumber,
                'type': self.filingType,
                'dateb': self.end_date,
                'datea': self.start_date,
                'owner': 'exclude',
                'output': '',
                'count': '100'}
            try:
                companyResponse = requests.get(url=r"https://www.sec.gov/cgi-bin/browse-edgar", params=filingParameters,
                                            headers=self.header)
                companyResponse.raise_for_status()
                companyParser = BeautifulSoup(companyResponse.content, 'html.parser')
                documentLink = companyParser.find("a", {"id": "documentsbutton"})
                if documentLink:
                    documentURL = self.baseURL + documentLink["href"]
                    print(f"Document Link: {documentURL}")
                    self.download_document(documentURL)
                else:
                    print("Document link not found.")
            except requests.exceptions.RequestException as e:
                print(f"Company or Calculation Report Request Error: {e}")
            except Exception as e:
                print(f"Error: {e}")
        else:
            print("API data not available.")
    
    def download_document(self, documentURL):
        try:
            documentResponse = requests.get(documentURL, headers=self.header)
            documentResponse.raise_for_status()
            documentParser = BeautifulSoup(documentResponse.content, 'html.parser')
            xmlTable = documentParser.find("table", {"summary": "Data Files"})
            xmlTableData = xmlTable.find_all("td", {"scope": "row"})
            dataFilesTable = documentParser.find("table", summary="Data Files")
            if dataFilesTable:
                rows = dataFilesTable.find_all("tr")
                for row in rows:
                    columns = row.find_all("td")
                    if len(columns) >= 3 and "EXTRACTED XBRL INSTANCE DOCUMENT" in columns[1].text:
                        xbrlInstanceLink = self.baseURL + columns[2].find("a")["href"]
                        print(f"XBRL Instance Link: {xbrlInstanceLink}")
                        self.download_xbrl_instance(xbrlInstanceLink)
                        calculationLink = self.find_calculation_link(documentParser)
                        break
                else:
                    print("XBRL Instance data not found.")
            else:
                print("XBRL Instance data not found.")
        except requests.exceptions.RequestException as e:
            print(f"Document Request Error: {e}")
        except Exception as e:
            print(f"Error: {e}")
    
    def find_calculation_link(self, documentParser):
        try:
            xmlTableData = documentParser.find_all("td", {"scope": "row"})
            if xmlTableData:
                for i in range(len(xmlTableData) - 1):
                    if xmlTableData[i].getText() == "XBRL TAXONOMY EXTENSION CALCULATION LINKBASE DOCUMENT":
                        xbrlCalculationData = xmlTableData[i + 1].find("a")
                        if xbrlCalculationData:
                            calculationLink = self.baseURL + xbrlCalculationData["href"]
                            print(f"XBRL Calculation Linkbase: {calculationLink}")
                            return calculationLink
                        else:
                            print("XBRL Calculation data not found.")
                            return None
                else:
                    print("XBRL Calculation data not found.")
                    return None
            else:
                print("XBRL Calculation data not found.")
                return None
        except requests.exceptions.RequestException as e:
            print(f"XBRL Calculation Request Error: {e}")
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def download_xbrl_instance(self, xbrlInstanceLink):
        try:
            xbrlInstanceResponse = requests.get(xbrlInstanceLink, headers=self.header)
            xbrlInstanceResponse.raise_for_status()
            xbrlInstanceParser = BeautifulSoup(xbrlInstanceResponse.content, 'html.parser')
            # Add logic to process the XBRL instance document here
        except requests.exceptions.RequestException as e:
            print(f"XBRL Instance Request Error: {e}")
        except Exception as e:
            print(f"Error: {e}")
    
    def download_schema(self, schemaLink):
        try:
            schemaReportResponse = requests.get(schemaLink, headers=self.header)
            schemaReportResponse.raise_for_status()
            schemaReportParser = BeautifulSoup(schemaReportResponse.content, features="xml")
            financialStatements = schemaReportParser.find_all("link:calculationLink", {"xlink:type": "extended"})
            # Add logic to process the schema document here
        except requests.exceptions.RequestException as e:
            print(f"Schema Request Error: {e}")
        except Exception as e:
            print(f"Error: {e}")

Purpose:
The SecFilingDownloader class is designed to facilitate the download and processing of SEC filings, particularly XBRL documents, for a specified company within a given date range.

Class Initialization:

1. baseURL:
Description: The base URL for constructing document links.
Default Value: "https://www.sec.gov"

2. CIKNumber:
Description: The Central Index Key (CIK) number for the company.
Usage: Replace the initial value with the CIK number of the specific company you are interested in.

3. filingType:
Description: The type of filing to be downloaded (e.g., '10-K', '10-Q').
Usage: Specify the desired filing type based on your requirements.

4. start_date and end_date:
Description: The start and end dates for the filings.
Usage: Set the desired start and end dates in the 'YYYY-MM-DD' format based on your requirements.

5. header:
Description: Headers for the HTTP requests to mimic a user agent.
Default Value: A user agent string for Chrome on Windows.

6. apiData:
Description: Holds the JSON data obtained from the SEC API.
Default Value: None

7. data:
Description: Holds the filing statement data.
Default Value: {"statement": []}

Methods:

1. download_api_data():
Purpose: Downloads company data from the SEC API.
Usage: Invoked to obtain data required for subsequent steps.

2. download_company_filing():
Purpose: Downloads the company filing document.
Usage: Relies on the obtained API data to fetch the filing document link.

3. download_document(documentURL):
Purpose: Downloads the document (HTML) containing links to XBRL instances.
Usage: Extracts links to XBRL instances and calls download_xbrl_instance().

4. find_calculation_link(documentParser):
Purpose: Finds and returns the link to the XBRL calculation linkbase document.
Usage: Called within download_document().

5. download_xbrl_instance(xbrlInstanceLink):
Purpose: Downloads the XBRL instance document.
Usage: Called to download the XBRL instance document after obtaining the link.

6. download_schema(schemaLink):
Purpose: Downloads the XBRL schema (calculationLink) document.
Usage: Called to download the XBRL schema document after obtaining the link.

Important Note:
Ensure that the necessary dependencies (e.g., requests, BeautifulSoup) are installed to execute this class. Modify the initial values of CIKNumber, filingType, start_date, and end_date based on your specific requirements.

The class structure is designed to facilitate the download and processing of SEC filings related to XBRL instances. The provided methods can be extended to incorporate additional logic for processing and analyzing the obtained data.

In [5]:
# Instantiate the class and download data
sec_filing_downloader = SecFilingDownloader(CIKNumber, filingType, start_date, end_date)
sec_filing_downloader.download_api_data()
sec_filing_downloader.download_company_filing()

Document Link: https://www.sec.gov/Archives/edgar/data/27419/000002741923000015/0000027419-23-000015-index.htm
XBRL Instance Link: https://www.sec.gov/Archives/edgar/data/27419/000002741923000015/tgt-20230128_htm.xml

C:\Users\daron\anaconda3\lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

XBRL Calculation Linkbase: https://www.sec.gov/Archives/edgar/data/27419/000002741923000015/tgt-20230128_cal.xml

1. Instantiation:
The SecFilingDownloader class is instantiated with the specified parameters (CIKNumber, filingType, start_date, end_date).

2. Download API Data:

The download_api_data() method is called to retrieve data from the SEC API based on the provided CIK number.
3. Download Company Filing:
The download_company_filing() method is called to download the company's filing document.
This method utilizes the obtained API data to fetch the filing document link.

Important Note:
Make sure to replace CIKNumber, filingType, start_date, and end_date with your specific values before executing the code. Additionally, ensure that the necessary dependencies are installed to run the code successfully.

In [6]:
header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}
response = requests.get(f"https://data.sec.gov/api/xbrl/companyfacts/CIK{CIKNumber}.json", headers=header)
data = None

if response.ok:
    data = json.loads(response.content)
    #print(data)
else:
    print(response.status_code)
    print(response.reason)

In [7]:
# Initialize the HTML table with column headers and add DataTables script
html = """
    <table id="example" class="display">
        <thead>
            <tr>
                <th>Concept</th>
                <th>Report Type</th>
                <th>Report Number</th>
                <th>Fiscal Year</th>
                <th>Period Ending</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
"""

# Extract the start and end years from the provided dates
start_year = start_date.year
end_year = end_date.year

# Find the highest fiscal year within the specified range
highest_fiscal_year = max(
    int(unit["fy"]) for concept_data in data["facts"]["us-gaap"].values()
    for unit in concept_data.get("units", {}).get("USD", [])
    if unit["form"] == filingType and start_year <= int(unit["fy"]) <= end_year
)

# Loop through all concepts within the "us-gaap" namespace
for concept, concept_data in data["facts"]["us-gaap"].items():
    if "USD" in concept_data.get("units", {}):  # Check if "USD" exists in units
        units = concept_data["units"]["USD"]

        for unit in units:
            report_type = unit["form"]
            fiscal_year = int(unit["fy"])  # Extract the fiscal year as an integer

            # Check if the fiscal year matches the specified start and end years
            # or if it is equal to the highest fiscal year
            if (start_year <= fiscal_year <= end_year or fiscal_year == highest_fiscal_year) and report_type == filingType:
                # Add a table row for each concept and its associated data
                html += f"""
                <tr>
                    <td>{concept}</td>
                    <td>{report_type}</td>
                    <td>{unit["accn"]}</td>
                    <td>{fiscal_year}</td>
                    <td>{unit["end"]}</td>
                    <td>{locale.currency(unit["val"], grouping=True)}</td>
                </tr>"""

# Close the HTML table
html += """
        </tbody>
    </table>
"""

# Display the HTML table
display(HTML(html))

Purpose:
The provided HTML code initializes a table with column headers and adds DataTables script. It then populates the table with data based on specified criteria, such as report type, fiscal year, and period ending. Finally, the table is displayed.

HTML Table Structure:

html
"<table id="example" class="display">
    <thead>
        <tr>
            <th>Concept</th>
            <th>Report Type</th>
            <th>Report Number</th>
            <th>Fiscal Year</th>
            <th>Period Ending</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
    <!-- Data rows will be dynamically added here -->
    </tbody>
</table>"

Data Population:

1. Start and End Years:
Extracts the start and end years from the provided dates.

2. Highest Fiscal Year:
Finds the highest fiscal year within the specified range.

3. Loop Through Concepts:
Iterates through all concepts within the "us-gaap" namespace.

4. Data Filtering and Population:
Filters concepts based on the specified criteria (report type, fiscal year within range or highest fiscal year).
Adds a table row for each concept meeting the criteria.

Table Columns:

1. Concept:
Displays the concept name.

2. Report Type:
Displays the report type (e.g., '10-K', '10-Q').

3. Report Number:
Displays the report number associated with the concept.

4. Fiscal Year:
Displays the fiscal year associated with the concept.

5. Period Ending:
Displays the period ending associated with the concept.
6. Value:
Displays the value associated with the concept in currency format.

Important Note:
Ensure that the DataTables script is included or loaded in the environment for proper rendering of the interactive table. The provided HTML code is dynamically generated based on the specified criteria and is intended to be used in an environment that supports HTML rendering and JavaScript for DataTables functionality. Modify the code as needed for integration into your specific project or application.

In [8]:
# Parse the HTML content
soup = BeautifulSoup(html, 'html.parser')

# Extract table data
data = []
table = soup.find('table')
for row in table.find_all('tr'):
    cols = row.find_all('td')
    cols = [col.text.strip() for col in cols]
    data.append(cols)

# Create a DataFrame from the extracted data
df = pd.DataFrame(data, columns=["Concept", "Report Type", "Report Number", "Fiscal Year", "Period Ending", "Value"])

# Display the DataFrame
df

,Concept,Report Type,Report Number,Fiscal Year,Period Ending,Value
0,None,None,None,None,None,None
1,AccountsAndOtherReceivablesNetCurrent,10-K,0000027419-22-000007,2021,2021-01-30,"$631,000,000.00"
2,AccountsAndOtherReceivablesNetCurrent,10-K,0000027419-22-000007,2021,2022-01-29,"$835,000,000.00"
3,AccountsPayableCurrent,10-K,0000027419-22-000007,2021,2021-01-30,"$12,859,000,000.00"
4,AccountsPayableCurrent,10-K,0000027419-22-000007,2021,2022-01-29,"$15,478,000,000.00"
...,...,...,...,...,...,...
465,UnrecognizedTaxBenefitsIncreasesResultingFromP...,10-K,0000027419-22-000007,2021,2021-01-30,"$32,000,000.00"
466,UnrecognizedTaxBenefitsIncreasesResultingFromP...,10-K,0000027419-22-000007,2021,2022-01-29,"$11,000,000.00"
467,UnrecognizedTaxBenefitsThatWouldImpactEffectiv...,10-K,0000027419-22-000007,2021,2022-01-29,"$67,000,000.00"
468,EmployeeRelatedLiabilitiesCurrent,10-K,0000027419-22-000007,2021,2021-01-30,"$1,677,000,000.00"
469,EmployeeRelatedLiabilitiesCurrent,10-K,0000027419-22-000007,2021,2022-01-29,"$1,620,000,000.00"

Purpose:
The provided code parses HTML content, extracts table data, and creates a Pandas DataFrame from the extracted data. Finally, the DataFrame is displayed.

HTML Parsing and Data Extraction:
python
# Parse the HTML content
soup = BeautifulSoup(html, 'html.parser')

# Extract table data
data = []
table = soup.find('table')
for row in table.find_all('tr'):
    cols = row.find_all('td')
    cols = [col.text.strip() for col in cols]
    data.append(cols)
    
BeautifulSoup Usage:
Utilizes BeautifulSoup to parse HTML content.

Table Data Extraction:
Iterates through each row (<tr>) in the HTML table.
Finds all table cells (<td>) within each row.
Strips leading and trailing whitespaces from cell text.
Appends the row data as a list to the data list.

DataFrame Creation:
python
# Create a DataFrame from the extracted data
df = pd.DataFrame(data, columns=["Concept", "Report Type", "Report Number", "Fiscal Year", "Period Ending", "Value"])

Pandas DataFrame:
Uses Pandas to create a DataFrame (df) from the extracted data.
Specifies column names as ["Concept", "Report Type", "Report Number", "Fiscal Year", "Period Ending", "Value"].

Display DataFrame:
python

# Display the DataFrame
df

Display Output:
Outputs the Pandas DataFrame, which organizes and presents the table data in a structured tabular format.
    
Important Note:
This code assumes that the HTML structure conforms to the expected format with a table containing rows and cells. Ensure that the HTML content is correctly structured to match the extraction logic. Adjust the code accordingly if variations exist in the HTML structure.

In [9]:
df = pd.DataFrame(data, columns=["Concept", "Report Type", "Report Number", "Fiscal Year", "Period Ending", "Value"])

# Define a function to update and display the DataFrame
def update_displayed_dataframe():
    sort_by = sort_column_dropdown.value
    ascending = sort_order_dropdown.value == 'Ascending'
    search = search_textbox.value
    
    # Filter and sort the DataFrame
    filtered_df = df[df['Concept'].str.contains(search, case=False, na=False)]
    sorted_df = filtered_df.sort_values(by=sort_by, ascending=ascending)
    
    # Clear the previous output and display the updated DataFrame
    clear_output(wait=True)
    display(sorted_df.style)

# Create interactive widgets
sort_column_dropdown = widgets.Dropdown(
    options=df.columns,
    description='Sort by:',
    layout=widgets.Layout(width='200px')
)

sort_order_dropdown = widgets.Dropdown(
    options=['Ascending', 'Descending'],
    description='Order:',
    layout=widgets.Layout(width='200px')
)

search_textbox = widgets.Text(
    description='Search:',
    layout=widgets.Layout(width='200px')
)

update_button = widgets.Button(description='Update')

# Define a function to handle button click event
def on_button_click(b):
    update_displayed_dataframe()

# Attach the click event handler to the button
update_button.on_click(on_button_click)

# Display widgets and initial DataFrame
widget_box = widgets.HBox([sort_column_dropdown, sort_order_dropdown, search_textbox, update_button])
display(widget_box)

HBox(children=(Dropdown(description='Sort by:', layout=Layout(width='200px'), options=('Concept', 'Report Type…

Purpose:
The interactive widget-based system facilitates the update and display of a Pandas DataFrame (df) based on sorting, ordering, and searching criteria.

DataFrame Initialization:

Pandas DataFrame:
Creates a Pandas DataFrame (df) from the previously extracted data.
Specifies column names as ["Concept", "Report Type", "Report Number", "Fiscal Year", "Period Ending", "Value"].

Interactive Widget Setup:

Interactive Widgets:
sort_column_dropdown: Dropdown for selecting the column to sort by.
sort_order_dropdown: Dropdown for choosing sorting order ('Ascending' or 'Descending').
search_textbox: Textbox for entering search criteria.
update_button: Button triggering the update of the displayed DataFrame.

Function to Update and Display DataFrame:

Update and Display Function:
Captures current widget values.
Filters and sorts the DataFrame based on user selections.
Clears the previous output and displays the updated DataFrame.

Button Click Event Handling:

Button Click Event Handling:
Defines a function (on_button_click) to handle the button click event.
Attaches the click event handler to the update_button.

Widget and Initial DataFrame Display:

Widget Display:
Creates a horizontal box (HBox) containing the interactive widgets.
Displays the widget box.

Important Note:
This code assumes that the structure and content of the DataFrame are suitable for sorting, ordering, and searching operations. Adjustments may be needed based on specific DataFrame characteristics or user requirements.

In [10]:
# Display the initial DataFrame
update_displayed_dataframe()

In [11]:
# Sample data (replace with your actual data)
data = {
    "Concept": [
        "AccountsAndOtherReceivablesNetCurrent",
        "AccountsAndOtherReceivablesNetCurrent",
        # Add more data
    ],
    "Report Type": ["10-K", "10-K"],
    "Report Number": ["0000027419-22-000007", "0000027419-22-000007"],
    "Fiscal Year": [2021, 2021],
    "Period Ending": ["2021-01-30", "2022-01-29"],
    "Value": ["$631,000,000.00", "$835,000,000.00"],
}

df = pd.DataFrame(data, columns=["Concept", "Report Type", "Report Number", "Fiscal Year", "Period Ending", "Value"])

# Define a function to construct financial statements
def construct_financial_statements(df, categories, fiscal_year, period_ending):
    statements = {}
    
    for category in categories:
        filtered_df = df[df['Concept'].str.contains(category, case=False, na=False)]
        filtered_df = filtered_df[(filtered_df['Fiscal Year'] == fiscal_year) & (filtered_df['Period Ending'] == period_ending)]
        
        if not filtered_df.empty:
            # Process the filtered DataFrame, e.g., sum the values
            total_value = filtered_df['Value'].str.replace('[\$,]', '', regex=True).astype(float).sum()
            statements[category] = total_value
    
    return statements

# Define your financial statement categories
financial_categories = ["Income Statement", "Balance Sheet", "Cash Flow Statement"]

# Create interactive widgets
fiscal_year_dropdown = widgets.Dropdown(
    options=df['Fiscal Year'].unique(),
    description='Fiscal Year:',
    layout=widgets.Layout(width='200px')
)

period_ending_dropdown = widgets.Dropdown(
    options=df['Period Ending'].unique(),
    description='Period Ending:',
    layout=widgets.Layout(width='200px')
)

update_button = widgets.Button(description='Generate Financial Statements')

# Define a function to handle button click event
def on_button_click(b):
    fiscal_year = fiscal_year_dropdown.value
    period_ending = period_ending_dropdown.value
    statements = construct_financial_statements(df, financial_categories, fiscal_year, period_ending)
    clear_output(wait=True)
    
    # Create a formatted string to display the statements
    statement_str = ""
    for category, total_value in statements.items():
        statement_str += f"{category}: ${total_value:,.2f}\n"
    
    display(Markdown(statement_str))

# Attach the click event handler to the button
update_button.on_click(on_button_click)

# Display widgets and initial DataFrame
widget_box = widgets.HBox([fiscal_year_dropdown, period_ending_dropdown, update_button])
display(widget_box)

HBox(children=(Dropdown(description='Fiscal Year:', layout=Layout(width='200px'), options=(2021,), value=2021)…

In [12]:
print(df.head())

                                 Concept Report Type         Report Number  \
0  AccountsAndOtherReceivablesNetCurrent        10-K  0000027419-22-000007
1  AccountsAndOtherReceivablesNetCurrent        10-K  0000027419-22-000007

   Fiscal Year Period Ending            Value
0         2021    2021-01-30  $631,000,000.00
1         2021    2022-01-29  $835,000,000.00

In [13]:
# Handle missing values if any
df = df.dropna()

# Convert categorical variables into numerical format using one-hot encoding
df = pd.get_dummies(df)

In [ ]:
X = df.drop('Value', axis=1)
y = df['Value']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))